name: Deploy

on: 
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    types:
      # note: merging check is below in the jobs
      - closed

permissions:
  id-token: write
  contents: read

env:
  managementGroupPrefix: "GSM"
  location: "Australia East"

jobs:
  bicep_tenant_deploy:
    runs-on: ubuntu-latest
    environment: prod
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: OIDC Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true

      - name: Az CLI Deploy Management Groups
        id: create_mgs
        shell: bash
        run: |
          az deployment tenant create \
            --template-file src/managementGroups.bicep \
            --name test_create_mgs-${{ github.run_number }} \
            --location "$location"

      - name: Az CLI What-If Deploy Custom Policy Definitions
        id: test_create_policy_defs
        shell: bash
        run: |
          az deployment mg create \
            --template-file src/customPolicyDefinitions.bicep \
            --name create_policy_defs-${{ github.run_number }} \
            --location "$location" \
            --management-group-id "$managementGroupPrefix"

      - name: Az CLI What-If Deploy Custom Role Definitions
        id: test_create_role_defs
        shell: bash
        run: |
          az deployment mg create \
            --template-file src/customRoleDefinitions.bicep \
            --name create_role_defs-${{ github.run_number }} \
            --location "$location" \
            --management-group-id "$managementGroupPrefix"